---
- hosts: qa
  vars_files:
    - variables.yml
  tasks:
    - name: Execute Shell Commands
      shell: uname
      register: uname_result
    - debug: msg="{{uname_result.stdout }} {{variable1}}"  
